### ISSUE TITLE
Connectivity change broadcast receiver

### ISSUE THREAD

**Issue by sravan953** [kahluagenie/muzei-gopro#1]
If the device isn't connected to the internet at 00:00, the user has to manually refresh the wallpaper. So my proposal is to implement a `BroadcastReceiver` that listens to connectivity changes and fires the muzei art source service appropriately.

**Comment by kahluagenie** [comment]
Ah, good point! I'll make it happen :)

**Comment by sravan953** [comment]
If you don't mind, I'd like to fix the issue.

**Comment by kahluagenie** [comment]
Oh absolutely, pull requests are most welcome.

**Comment by sravan953** [comment]
Super!

**Comment by sravan953** [comment]
Going through the API reference - http://api.muzei.co/reference/com/google/android/apps/muzei/api/RemoteMuzeiArtSource.html

... seems like `RemoteMuzeiArtSource` should do this by itself.

**Comment by kahluagenie** [comment]
Ok, that's what I thought... I haven't been in that code in a while, so I thought my memory was failing me. I'll do more testing on this in the next couple of days to see what's up.
